### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by panigo** [nimaltd/gsm_v5#20]
Hello. I really like your job. I am using your libraries. Could you add MQTT work? Thank you.

**Comment by nimaltd** [comment]
Hello. I will add it after I needed it

**Comment by leech001** [comment]
> Hello. I really like your job. I am using your libraries. Could you add MQTT work? Thank you.

If you really need it, you can use this implementation [https://github.com/leech001/SIM800MQTT](https://github.com/leech001/SIM800MQTT)

**Comment by nimaltd** [comment]
@leech001 🤗🤗🤗

**Comment by panigo** [comment]
Благодарю.
