### ISSUE TITLE
I cannot receive incoming messages.

### ISSUE THREAD

**Issue by a-topkir** [nimaltd/gsm_v5#28]
![10](https://user-images.githubusercontent.com/63725705/114612892-60110180-9cab-11eb-9f3b-84471b78200c.PNG)
![22](https://user-images.githubusercontent.com/63725705/114612894-60a99800-9cab-11eb-90c2-10de3eccc826.PNG)

Hi 

It doesn't go into line 360 ​​at all. And 
It goes to line 351 without entering the 348th and 350th lines. I cannot read incoming messages. When I run it step by step, I see the previous messages in the array, but it never goes into the "gsm_callback_newMsg (char * number, gsm_time_t time, char * msg)" function.

**Comment by apie135** [comment]
**same problem**

I can not receive a message, too. It goes into the "gsm_callback_newMsg ()" function, but not the brek pointe I put into the function.

**Comment by nimaltd** [comment]
Hi. All other is working? only new message callback does not work?

**Comment by ch** [comment]
You should register callback function  usart interrupt, for HAL:

`void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart == UART_SIM800) {
        Sim800_RxCallBack();
    }
}`

**Comment by apie135** [comment]
![3](https://user-images.githubusercontent.com/43476088/114837417-59ce7280-9ddc-11eb-95d7-2eb07fdf5a90.JPG)

Is this spelling wrong?

![Ekran Alıntısı](https://user-images.githubusercontent.com/43476088/114838016-f6911000-9ddc-11eb-907a-a5c4ec77363f.JPG)

read me, it writes like this. "Sim800_RxCallBack ();" where is the reference.

`void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart == UART_SIM800) {
        Sim800_RxCallBack();
    }
}`

**Comment by apie135** [comment]
@nimaltd  Yes I can send message but I cant Receive message

**Comment by ch** [comment]
@apie135 sorry, 
gsm_rxCallback :)

Do you use LL or HAL?

**Comment by apie135** [comment]
I use LL Library for Usart

**Comment by apie135** [comment]
I can Receive message past. Bus new message I cant

**Comment by nimaltd** [comment]
I changed ATC to previews version. please try again.

**Comment by apie135** [comment]
I will retun home today. I am going to try totay. I will give information thankn you

**Comment by apie135** [comment]
Where can I download the previous version.

**Comment by apie135** [comment]
Hi @nimaltd gsm_callback_newMsg

**Comment by apie135** [comment]
![dfdf](https://user-images.githubusercontent.com/43476088/115148743-aed2e880-a069-11eb-8d71-450658c72369.PNG)


> Not resolved

It goes into line 351, without going over the 350th line. Since this many messages are full, he does not receive new messages. I clear the messages for en and then start it. It goes on line 351, but still doesn't enter the function. "gsm_callback_newMsg". As you said, I've installed the previous atc.

**Comment by nimaltd** [comment]
@apie135 i dont know why. Do you want I connect to your system via anydesk and debug it?

**Comment by nimaltd** [comment]
@apie135 please clean your project and compile again. Update  keil. And try again. It should be works.
I am using this library without any problem

**Comment by apie135** [comment]
@nimaltd 
I recompiled the project and had the same problem again. If you have a link, we can do it. Whenever you are available? Thank you.
I would be glad if you can connect to my computer.

**Comment by nimaltd** [comment]
I am available now.

**Comment by apie135** [comment]
thank you for your interest.  I sent you a mail.

**Comment by apie135** [comment]
Hi nimal dou you connect my pc via anydesk

**Comment by nimaltd** [comment]
please send your id via email  nimaltd@yahoo.com
