### ISSUE TITLE
[GSM ATC] AT+SMCONF="CID",1 ERROR [GSM] gprs_mqttConnect() failed!

### ISSUE THREAD

**Issue by billiri** [nimaltd/gsm_v5#29]
I use sim800c and got this error

**Comment by nimaltd** [comment]
you should update firmware. contact simcom

**Comment by billiri** [comment]
I update firmware sim800c to 1418B07SIM800C24_BT.RAR and got same error

**Comment by billiri** [comment]
try 1418B05SIM800C24.rar and got this error too

**Comment by billiri** [comment]
//  set CID to 1
  sprintf((char*)gsm.buffer, "AT+SMCONF=\"CID\",1\r\n");
  if (gsm_command((char*)gsm.buffer, 1000 , NULL, 0, 2, "\r\nOK\r\n", "\r\nERROR\r\n") != 1)
  {
    gsm_printf("[GSM] gprs_mqttConnect() failed!\r\n");
    gsm_unlock();
    return false;
  }
trouble here, gprs connect succesful but mqtt got error here

**Comment by nimaltd** [comment]
https://nimaltd.github.io/

**Comment by youssef02** [comment]
I have sim800C version 1418B08SIM800C24_BT
and have the same problem, I will try to send simcom an email, that if they reply.

**Comment by youssef02** [comment]
Update, 1 day after sending the email, In the meantime I will try to update the firmware using uart

**Comment by hbend1li** [comment]
always i got error when i upload firmware.
```
mtkdownload /dev/ttyACM0 ROM_VIVA Y
configure complete
start send and receive data
fcntl=0
isatty success!
fd-open=3
Filename : ROM_VIVA
Filesize : 2151984 bytes
 len=2151984	 
Power On/Reset Target
Starting flash write
Start to Erase flash!
Please wait for flash erase finished!
SEND 1 Bytes 81
SEND 128 Bytes 
52	52	 ... 	52	02	reading erase

recv  1 Byte 	00

recv  1 Byte 	08
Start to program ROM file to flash!
Error: writing flash error!
``` 

problem resolved, i change USB bridge.
