### ISSUE TITLE
Message read error

### ISSUE THREAD

**Issue by ninjas005** [nimaltd/gsm_v5#50]
It says 
`[GSM] msg_isTextMode() failed!`
the ans variable is returning 2.
`[GSM] msg_read(1) failed!`

how to read sms from the sim800 module

**Comment by ninjas005** [comment]
found out the issue may be this could be due to 
`[GSM] msg_selectStorage() failed!`

How could i solve the problem?
I had set it to store in the simcard. but is not working

**Comment by ninjas005** [comment]
Yes, I can send SMS and on another project publish MQTT. didn't try to receive any. I think I am missing something in receiving SMS. when I remove the inserted sim card back in a mobile, all the SMS got received.

**Comment by ninjas005** [comment]
I tried with a different sim card and different network operator and it worked.

**Comment by ninjas005** [comment]
may be some problem wit the other sim card

**Comment by nimaltd** [comment]
try to change sms configuration and do again
